INSERT INTO `kategory` (`id`, `name`) VALUES (1, 'Фрукты');
INSERT INTO `kategory` (`id`, `name`) VALUES (2, 'Овощи');
INSERT INTO `kategory` (`id`, `name`) VALUES (3, 'Зелень, салаты');
INSERT INTO `kategory` (`id`, `name`) VALUES (4, 'Грибы');
INSERT INTO `kategory` (`id`, `name`) VALUES (5, 'Ягоды');
INSERT INTO `kategory` (`id`, `name`) VALUES (6, 'Орехи, сухофрукты, семечки');
INSERT INTO `kategory` (`id`, `name`) VALUES (7, 'Молоко');
INSERT INTO `kategory` (`id`, `name`) VALUES (8, 'Растительные напитки');
INSERT INTO `kategory` (`id`, `name`) VALUES (9, 'Молочные напитки');
INSERT INTO `kategory` (`id`, `name`) VALUES (10, 'Кисломолочные продукты');
INSERT INTO `kategory` (`id`, `name`) VALUES (11, 'Сметана');
INSERT INTO `kategory` (`id`, `name`) VALUES (12, 'Сливочное масло, маргарин');
INSERT INTO `kategory` (`id`, `name`) VALUES (13, 'Мясо');
INSERT INTO `kategory` (`id`, `name`) VALUES (14, 'Птица');
INSERT INTO `kategory` (`id`, `name`) VALUES (15, 'Полуфабрикаты из мяса, птицы');
INSERT INTO `kategory` (`id`, `name`) VALUES (16, 'Субпродукты');
INSERT INTO `kategory` (`id`, `name`) VALUES (17, 'Халяль');
INSERT INTO `kategory` (`id`, `name`) VALUES (18, 'Рыба');
INSERT INTO `kategory` (`id`, `name`) VALUES (19, 'Морепродукты');
INSERT INTO `kategory` (`id`, `name`) VALUES (20, 'Полуфабрикаты из рыбы, морепродуктов');
INSERT INTO `kategory` (`id`, `name`) VALUES (21, 'Рыбные деликатесы');
INSERT INTO `kategory` (`id`, `name`) VALUES (22, 'Икра');
INSERT INTO `kategory` (`id`, `name`) VALUES (23, 'Пельмени, вареники');
INSERT INTO `kategory` (`id`, `name`) VALUES (24, 'Овощи, смеси, грибы');
INSERT INTO `kategory` (`id`, `name`) VALUES (25, 'Фрукты, ягоды');
INSERT INTO `kategory` (`id`, `name`) VALUES (26, 'Рыба, морепродукты');
INSERT INTO `kategory` (`id`, `name`) VALUES (27, 'Мясо, птица');
INSERT INTO `kategory` (`id`, `name`) VALUES (28, 'Полуфабрикаты');
INSERT INTO `kategory` (`id`, `name`) VALUES (29, 'Крупы, бобовые');
INSERT INTO `kategory` (`id`, `name`) VALUES (30, 'Макароны, паста');
INSERT INTO `kategory` (`id`, `name`) VALUES (31, 'Хлопья, мюсли, отруби');
INSERT INTO `kategory` (`id`, `name`) VALUES (32, 'Мука');
INSERT INTO `kategory` (`id`, `name`) VALUES (33, 'Для выпечки, десертов, напитков');
INSERT INTO `kategory` (`id`, `name`) VALUES (34, 'Сахар, соль');
INSERT INTO `kategory` (`id`, `name`) VALUES (35, 'Вода');
INSERT INTO `kategory` (`id`, `name`) VALUES (36, 'Растительные напитки');
INSERT INTO `kategory` (`id`, `name`) VALUES (37, 'Соки, нектары, морсы');
INSERT INTO `kategory` (`id`, `name`) VALUES (38, 'Газированные напитки');
INSERT INTO `kategory` (`id`, `name`) VALUES (39, 'Холодный чай');
INSERT INTO `kategory` (`id`, `name`) VALUES (40, 'Квас');
INSERT INTO `kategory` (`id`, `name`) VALUES (41, 'Энергетические напитки');
INSERT INTO `kategory` (`id`, `name`) VALUES (42, 'Безалкогольное пиво, вино');
INSERT INTO `kategory` (`id`, `name`) VALUES (43, 'Heineken');
INSERT INTO `kategory` (`id`, `name`) VALUES (44, 'Coca Cola');
INSERT INTO `kategory` (`id`, `name`) VALUES (45, 'Aqua Minerale');
INSERT INTO `kategory` (`id`, `name`) VALUES (46, 'Колбасы');
INSERT INTO `kategory` (`id`, `name`) VALUES (47, 'Сосиски, сардельки');
INSERT INTO `kategory` (`id`, `name`) VALUES (48, 'Ветчина, деликатесы');
INSERT INTO `kategory` (`id`, `name`) VALUES (49, 'Вязанка');
INSERT INTO `kategory` (`id`, `name`) VALUES (50, 'Фрукты');
INSERT INTO `kategory` (`id`, `name`) VALUES (51, 'Овощи');
INSERT INTO `kategory` (`id`, `name`) VALUES (52, 'Зелень, салаты');
INSERT INTO `kategory` (`id`, `name`) VALUES (53, 'Грибы');
INSERT INTO `kategory` (`id`, `name`) VALUES (54, 'Ягоды');
INSERT INTO `kategory` (`id`, `name`) VALUES (55, 'Орехи, сухофрукты, семечки');
INSERT INTO `kategory` (`id`, `name`) VALUES (56, 'Молоко');
INSERT INTO `kategory` (`id`, `name`) VALUES (57, 'Растительные напитки');
INSERT INTO `kategory` (`id`, `name`) VALUES (58, 'Молочные напитки');
INSERT INTO `kategory` (`id`, `name`) VALUES (59, 'Кисломолочные продукты');
INSERT INTO `kategory` (`id`, `name`) VALUES (60, 'Сметана');
INSERT INTO `kategory` (`id`, `name`) VALUES (61, 'Сливочное масло, маргарин');
INSERT INTO `kategory` (`id`, `name`) VALUES (62, 'Мясо');
INSERT INTO `kategory` (`id`, `name`) VALUES (63, 'Птица');
INSERT INTO `kategory` (`id`, `name`) VALUES (64, 'Полуфабрикаты из мяса, птицы');
INSERT INTO `kategory` (`id`, `name`) VALUES (65, 'Субпродукты');
INSERT INTO `kategory` (`id`, `name`) VALUES (66, 'Рыба');
INSERT INTO `kategory` (`id`, `name`) VALUES (67, 'Морепродукты');
INSERT INTO `kategory` (`id`, `name`) VALUES (68, 'Полуфабрикаты из рыбы, морепродуктов');
INSERT INTO `kategory` (`id`, `name`) VALUES (69, 'Рыбные деликатесы');
INSERT INTO `kategory` (`id`, `name`) VALUES (70, 'Икра');
INSERT INTO `kategory` (`id`, `name`) VALUES (71, 'Пельмени, вареники');
INSERT INTO `kategory` (`id`, `name`) VALUES (72, 'Овощи, смеси, грибы');
INSERT INTO `kategory` (`id`, `name`) VALUES (73, 'Фрукты, ягоды');
